version: '3.8'

services:

  frontend:
    image: frontend
    container_name: frontend
    networks:
      - app-network
    ports:
      - "4200:8080"
    build: ./frontend

  cluster-manager:
    image: backend
    container_name: cluster-manager
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - FRONTEND_ORIGIN=http://localhost:4200
      - APPLICATION_PORT=8080
      - SPRING_PROFILES_ACTIVE=cluster_manager
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node1:
    profiles: ['test']
    image: backend
    container_name: node1
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node1
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - SPRING_PROFILES_ACTIVE=backup_node
      - NODE_ID=node1
      - APPLICATION_PORT=8080
    ports:
      - "18081:8080"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node2:
    profiles: ['test']
    image: backend
    container_name: node2
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node2
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - SPRING_PROFILES_ACTIVE=backup_node
      - NODE_ID=node2
      - APPLICATION_PORT=8080
    ports:
      - "18082:8080"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: bcm
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d bcm"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge