services:

  frontend:
    image: frontend
    container_name: frontend
    networks:
      - app-network
    ports:
      - "4200:8080"
    build: ./frontend

  cluster-manager:
    image: backend
    container_name: cluster_manager
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      # Default values are taken
      - ALLOWED_ORIGINS=http://localhost:4200,http://node1:8081,http://node2:8082
      #- APPLICATION_PORT=8080
      - SPRING_PROFILES_ACTIVE=cluster_manager
      - NODE_ADDRESS=cluster-manager:8080
      - BM_ADDRESS=node2:8082
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node1:
    profiles: ['test']
    image: backend
    container_name: node1
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node1
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - SPRING_PROFILES_ACTIVE=backup_node
      - NODE_ID=node1
      - APPLICATION_PORT=8081
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node1:8081
      - BM_ADDRESS=node2:8082
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node2:
    profiles: ['test']
    image: backend
    container_name: node2
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node2
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - SPRING_PROFILES_ACTIVE=backup_manager,backup_node
      - NODE_ID=node2
      - APPLICATION_PORT=8082
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node2:8082
      - BM_ADDRESS=node2:8082
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node3:
    profiles: [ 'test' ]
    image: backend
    container_name: node3
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node3
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - SPRING_PROFILES_ACTIVE=backup_node
      - NODE_ID=node3
      - APPLICATION_PORT=8083
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node3:8083
      - BM_ADDRESS=node2:8082
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node4:
    profiles: [ 'test' ]
    image: backend
    container_name: node4
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node4
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - SPRING_PROFILES_ACTIVE=backup_node
      - NODE_ID=node4
      - APPLICATION_PORT=8084
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node4:8084
      - BM_ADDRESS=node2:8082
    ports:
      - "8084:8084"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node5:
    profiles: [ 'test' ]
    image: backend
    container_name: node5
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node5
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - SPRING_PROFILES_ACTIVE=backup_node
      - NODE_ID=node5
      - APPLICATION_PORT=8085
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node5:8085
      - BM_ADDRESS=node2:8082
    ports:
      - "8085:8085"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node6:
    profiles: [ 'test' ]
    image: backend
    container_name: node6
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node6
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - SPRING_PROFILES_ACTIVE=backup_node
      - NODE_ID=node6
      - APPLICATION_PORT=8086
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node6:8086
      - BM_ADDRESS=node2:8082
    ports:
      - "8086:8086"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: bcm
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d bcm"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge