services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-targets.json:/etc/prometheus/prometheus-targets.json

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
  frontend:
    image: frontend
    container_name: frontend
    networks:
      - app-network
    ports:
      - "4200:8080"
    build: ./frontend

  cluster-manager:
    image: backend
    container_name: cluster-manager
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node0
      - CM_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm
      - R2DBC_BN_URL=r2dbc:postgresql://postgres:5432/bcm_node0
      - R2DBC_CM_URL=r2dbc:postgresql://postgres:5432/bcm
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - NODE_ID=node0
      # Default values are taken
      - ALLOWED_ORIGINS=http://localhost:4200
      - CM_ADDRESS=cluster-manager:8080
      #- APPLICATION_PORT=8080
      - NODE_ADDRESS=cluster-manager:8080
      - SPRING_PROFILES_ACTIVE=cluster_manager
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node1:
    profiles: ['test']
    image: backend
    container_name: node1
    restart: on-failure
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node1
      - R2DBC_BN_URL=r2dbc:postgresql://postgres:5432/bcm_node1
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - NODE_ID=node1
      - APPLICATION_PORT=8081
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node1:8081
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node2:
    profiles: ['test']
    image: backend
    container_name: node2
    restart: on-failure
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node2
      - R2DBC_BN_URL=r2dbc:postgresql://postgres:5432/bcm_node2
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - NODE_ID=node2
      - APPLICATION_PORT=8082
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node2:8082
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node3:
    profiles: [ 'test' ]
    image: backend
    container_name: node3
    restart: on-failure
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node3
      - R2DBC_BN_URL=r2dbc:postgresql://postgres:5432/bcm_node3
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - NODE_ID=node3
      - APPLICATION_PORT=8083
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node3:8083
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node4:
    profiles: [ 'test' ]
    image: backend
    container_name: node4
    restart: on-failure
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node4
      - R2DBC_BN_URL=r2dbc:postgresql://postgres:5432/bcm_node4
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - NODE_ID=node4
      - APPLICATION_PORT=8084
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node4:8084
    ports:
      - "8084:8084"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node5:
    profiles: [ 'test' ]
    image: backend
    container_name: node5
    restart: on-failure
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node5
      - R2DBC_BN_URL=r2dbc:postgresql://postgres:5432/bcm_node5
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - NODE_ID=node5
      - APPLICATION_PORT=8085
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node5:8085
    ports:
      - "8085:8085"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  node6:
    profiles: [ 'test' ]
    image: backend
    container_name: node6
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/bcm_node6
      - R2DBC_BN_URL=r2dbc:postgresql://postgres:5432/bcm_node6
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - NODE_ID=node6
      - APPLICATION_PORT=8086
      - CM_ADDRESS=cluster-manager:8080
      - NODE_ADDRESS=node6:8086
    ports:
      - "8086:8086"
    networks:
      - app-network
    depends_on:
      - postgres
    build: ./backend

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: bcm
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d bcm"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge