global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "BCM"
    metrics_path: "/actuator/prometheus"
    file_sd_configs:
      - files:
          - './prometheus-targets.json'
        refresh_interval: 30s