# Note for creating profiles:
# There are profiles for each node type for role-dependant bean activation, etc.
# Regarding differences between local-dev and prod setup there are two general configs that can include all the different settings regarding the environment the application is deployed in
# and can be applied for all node-types. e.g. profile=dev,cluster_manager; profile=prod,cluster_manager


spring:
  application:
    name: bcm
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  flyway:
    enabled: true
    locations: classpath:db/migration/base
    baseline-on-migrate: true
    #locations: classpath:db/migration/base
    #url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/bcm_node0}
    #user: ${POSTGRES_USER:appuser}
    #password: ${POSTGRES_PASSWORD:apppassword}
  r2dbc:
    bn:
      url: ${R2DBC_BN_URL:r2dbc:postgresql://localhost:5432/bcm_node0}
      username: ${POSTGRES_USER:appuser}
      password: ${POSTGRES_PASSWORD:apppassword}
  datasource:
    hikari:
      jdbc-url: ${DATASOURCE_URL:jdbc:postgresql://postgres:5432/bcm_node0}
      username: ${POSTGRES_USER:appuser}
      password: ${POSTGRES_PASSWORD:apppassword}
      driver-class-name: org.postgresql.Driver
  logging:
    level:
      root: INFO
      com.bcm: DEBUG

server:
  port: ${APPLICATION_PORT:8080}

application:
  cors:
    allowed-origin: ${ALLOWED_ORIGINS:http://localhost:4200}
  cm:
    public-address: ${CM_ADDRESS}
  node:
    public-address: ${NODE_ADDRESS}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
  metrics:
    enable:
      jvm: true
      system: true
      process: true
    export:
      simple:
        enabled: true

# mybatis:
#   type-aliases-package: com.bcm.shared.model.database
#   configuration:
#     map-underscore-to-camel-case: true
#     jdbc-type-for-null: OTHER



# Node-type profiles (only one should be activated at the same time and can be combined with prod / dev
---
spring:
  config:
    activate:
      on-profile: cluster_manager

  r2dbc:
    cm:
      url: ${R2DBC_CM_URL:r2dbc:postgresql://localhost:5432/bcm}
      username: ${POSTGRES_USER:appuser}
      password: ${POSTGRES_PASSWORD:apppassword}
  flyway:
    locations: classpath:db/migration/base,classpath:db/migration/cluster_manager

  cm-datasource:
    hikari:
      jdbc-url: ${CM_DATASOURCE_URL:jdbc:postgresql://postgres:5432/bcm}
      username: ${POSTGRES_USER:appuser}
      password: ${POSTGRES_PASSWORD:apppassword}
      driver-class-name: org.postgresql.Driver

  #flyway:
  #  locations: classpath:db/migration/cluster_manager
  #  url: ${CM_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bcm}
  #  user: ${POSTGRES_USER:appuser}
  #  password: ${POSTGRES_PASSWORD:apppassword}
server:
  servlet:
    session:
      timeout: 30m
---
# Development profile
spring:
  config:
    activate:
      on-profile: dev





---
# Test profile (H2)
spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: true
