# Note for creating profiles:
# There are profiles for each node type for role-dependant bean activation, etc.
# Regarding differences between local-dev and prod setup there are two general configs that can include all the different settings regarding the environment the application is deployed in
# and can be applied for all node-types. e.g. profile=dev,cluster_manager; profile=prod,cluster_manager


spring:
  application:
    name: bcm
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  flyway:
    enabled: true
    locations: classpath:db/migration/base
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/bcm_node0}
    user: ${POSTGRES_USER:appuser}
    password: ${POSTGRES_PASSWORD:apppassword}
  datasource:
    bn:
      url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/bcm_node0}
      username: ${POSTGRES_USER:appuser}
      password: ${POSTGRES_PASSWORD:apppassword}
      driverClassName: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
  logging:
    level:
      root: INFO
      com.bcm: INFO
server:
  port: ${APPLICATION_PORT:8080}
application:
  cors:
    allowed-origin: ${ALLOWED_ORIGINS:http://localhost:4200}
  cm:
    public-address: ${CM_ADDRESS}
  node:
    public-address: ${NODE_ADDRESS}

mybatis:
  type-aliases-package: com.bcm.shared.model.database
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: OTHER



# Node-type profiles (only one should be activated at the same time and can be combined with prod / dev
---
spring:
  config:
    activate:
      on-profile: cluster_manager
  datasource:
    cm:
      url: ${CM_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bcm}
      username: ${POSTGRES_USER:appuser}
      password: ${POSTGRES_PASSWORD:apppassword}
      driverClassName: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
  flyway:
    locations: classpath:db/migration/cluster_manager
    url: ${CM_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bcm}
    user: ${POSTGRES_USER:appuser}
    password: ${POSTGRES_PASSWORD:apppassword}
server:
  servlet:
    session:
      timeout: 30m
---
# Development profile
spring:
  config:
    activate:
      on-profile: dev





---
# Test profile (H2)
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true